### ISSUE TITLE
Keep VTI format?

### ISSUE THREAD

**Issue by andrewwinters5000** [trixi-framework/Trixi2Vtk.jl#60]
Currently, the `vti` format only works for `TreeMesh` without AMR. Do we want fix this and make the VTI format available across all mesh types both with and without AMR?

**Comment by sloede** [comment]
I haven't used the VTI format anymore for at least 1.5 years. I originally implemented it because there were some mesh imprinting issues in the very beginning of Trixi's lifetime. If nobody has been using it, and nobody is willing to fix it, I'd be ok with removing it (although this would be a breaking change and should be reflected in the version number accordingly).
